<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="AlleRealWerte" Id="{472ba1ba-8941-4ae2-886b-7b104aa65596}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM AlleRealWerte
VAR
	myRealWerte : ARRAY [1..30,1..2] OF STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	(*
		Temp_VD_in.REAL_VAR	,	
		Temp_VD_in_rev.REAL_VAR	,
		Temp_VD_out.REAL_VAR,	
		Temp_VD_out_rev.REAL_VAR,
		Temp_VD_surface.REAL_VAR,
		Temp_VF_in.REAL_VAR	,	
		Temp_VF_out.REAL_VAR,
		Temp_VD_defrost_in.REAL_VAR	,
		Temp_VD_defrost_out.REAL_VAR, 
		Temp_KP_in.REAL_VAR	,	
		Temp_KP_out.REAL_VAR,
		Temp_vor_EV.REAL_VAR,		
		Temp_vor_EV_rev.REAL_VAR];
		*)]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>